package View;

import Connect.JoConnentMySQL;
import java.sql.*;
import javax.swing.JOptionPane;

public class frm_Register extends javax.swing.JFrame {

    JoConnentMySQL jocon = new JoConnentMySQL("localhost", "root", "@min2020", "db_myschool");

    public frm_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        myLable1 = new Componnet.MyLable();
        txtuser = new Componnet.myTextfield();
        btnRegister = new javax.swing.JButton();
        myLable2 = new Componnet.MyLable();
        myLable3 = new Componnet.MyLable();
        myLable4 = new Componnet.MyLable();
        txtconfirm = new javax.swing.JPasswordField();
        txtpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myLable1.setText("ລະຫັດຜ່ານ");
        jPanel1.add(myLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, -1));

        btnRegister.setBackground(new java.awt.Color(0, 153, 153));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 210, 40));

        myLable2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myLable2.setText("ລົງທະບຽນ");
        myLable2.setFont(new java.awt.Font("Phetsarath OT", 0, 24)); // NOI18N
        jPanel1.add(myLable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 210, -1));

        myLable3.setText("ຊື່ຜູ້ໃຊ້ງານ");
        jPanel1.add(myLable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        myLable4.setText("ຢືນຢັນລະຫັດຜ່ານ");
        jPanel1.add(myLable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));
        jPanel1.add(txtconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 210, 25));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, 25));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(452, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {
            String sql = "INSERT INTO tb_user VALUES (?,?,?)";
            PreparedStatement pre = jocon.getConnectMySQL().prepareStatement(sql);
            pre.setString(1, null);
            pre.setString(2, txtuser.getText());
            pre.setString(3, txtpassword.getText());
            if (txtpassword.getText().equals(txtconfirm.getText())) {
                if (pre.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(null, "Registered");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Can not Register");
                }
            } else {
                JOptionPane.showMessageDialog(null, "password Not Colect");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel jPanel1;
    private Componnet.MyLable myLable1;
    private Componnet.MyLable myLable2;
    private Componnet.MyLable myLable3;
    private Componnet.MyLable myLable4;
    private javax.swing.JPasswordField txtconfirm;
    private javax.swing.JPasswordField txtpassword;
    private Componnet.myTextfield txtuser;
    // End of variables declaration//GEN-END:variables
}
